[package]
name = "rust_uuid_lib"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["staticlib", "cdylib"]  # for iOS, Android, Desktop

[dependencies]
uuid = { version = "1", features = ["v4", "js"] }  # UUID v4 generator
wasm-bindgen = "0.2"